const ADD_ITEM = 'ADD_ITEM'
const ADD_MORE = 'ADD_MORE'
const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
const REDUCE_QUANTITY = 'REDUCE_QUANTITY'
const EMPTY_CART = 'EMPTY_CART'
const REMOVE_ITEM = 'REMOVE_ITEM'
const SAVE_AUTH_INFO = 'SAFE_AUTH_INFO'

const GET_ADDRESS_REQUEST = 'GET_ADDRESS_REQUEST'
const GET_ADDRESS_SUCCESS = 'GET_ADDRESS_SUCCESS'
const GET_ADDRESS_FAILED = 'GET_ADDRESS_FAILED'

const ADD_ADDRESS_REQUEST = 'ADD_ADDRESS_REQUEST'
const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS'
const ADD_ADDRESS_FAILED = 'ADD_ADDRESS_FAILED'

const EDIT_ADDRESS_REQUEST = 'EDIT_ADDRESS_REQUEST'
const EDIT_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS'
const EDIT_ADDRESS_FAILED = 'EDIT_ADDRESS_FAILED'

const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
const CHECKOUT_FAILED = 'CHECKOUT_FAILED'

const RENEW_TOKEN_REQUEST = 'RENEW_TOKEN_REQUEST'

export {
	ADD_ITEM,
	ADD_MORE,
	GET_ALL_PRODUCTS,
	REDUCE_QUANTITY,
	EMPTY_CART,
	REMOVE_ITEM,
	SAVE_AUTH_INFO,
	GET_ADDRESS_REQUEST,
	GET_ADDRESS_SUCCESS,
	GET_ADDRESS_FAILED,
	ADD_ADDRESS_REQUEST,
	ADD_ADDRESS_SUCCESS,
	ADD_ADDRESS_FAILED,
	EDIT_ADDRESS_REQUEST,
	EDIT_ADDRESS_SUCCESS,
	EDIT_ADDRESS_FAILED,
	CHECKOUT_REQUEST,
	CHECKOUT_SUCCESS,
	CHECKOUT_FAILED,
	RENEW_TOKEN_REQUEST
}